FROM ubuntu:xenial
# FROM postgres:10.3
# FROM carto/bigmetadata_postgres
# FROM carto/bigmetadata_postgres_10

# RUN apt-get -y update
# RUN apt-get -y install build-essential libpq-dev postgresql-server-dev-10 # compiling PG extensions

